Hotfix/v1.0.0 3
in2workspace/in2-wallet-core-api pull request #26
Opened 2024-04-03 13:53 UTC by rubenmodamioin2

2024-04-04 11:05 UTC, oriolcanades requested changes

2024-04-04 11:05 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/AuthorizationResponseService.java
> +    Mono<Void> sendAuthorizationResponseForDome(String vpToken, VcSelectorResponse vcSelectorResponse);
sendDomeAuthorizationResponse() better understanding ;)

2024-04-04 11:05 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/AuthorizationResponseServiceImpl.java
> +    public Mono<Void> sendAuthorizationResponseForDome(String vpToken, VcSelectorResponse vcSelectorResponse) {
sendDomeAuthorizationResponse()

2024-04-04 11:05 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/AuthorizationResponseServiceImpl.java
> +        return postRequest(vcSelectorResponse.redirectUri(), headers, xWwwFormUrlencodedBody)
this do not pass

2024-04-04 11:05 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/AuthorizationResponseServiceImpl.java
> +        return postRequest(urlWithState, headers,body)
this do not pass

2024-04-04 11:05 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/PresentationServiceImpl.java
> +                                .doOnSuccess(verifiablePresentation -> log.info("ProcessID: {} - Verifiable Presentation created successfully for dome: {}", processId, verifiablePresentation))
Change "DOME Verifiable Presentation created successfully"

2024-04-04 11:05 UTC, oriolcanades commented on src/main/java/es/in2/wallet/infrastructure/core/controller/VerifiablePresentationController.java
> +                        if (DOME_REDIRECT_URI_PATTERN.matcher(vcSelectorResponse.redirectUri()).matches()){
Take care about your code readability, please

2024-04-04 11:05 UTC, oriolcanades commented on src/main/resources/application.yml
> +#auth-server:
why do you comment this block of code?

2024-04-04 12:54 UTC, oriolcanades submitted a review, later dismissed

2024-04-05 08:43 UTC, oriolcanades requested changes

2024-04-05 08:43 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/PreAuthorizedServiceImpl.java
> +                .onErrorResume(e -> Mono.error(new InvalidCredentialsException("Incorrect PIN or expired access token" + e)));
Si hace referencia al PIN, no lo llamaría InvalidCredentialException. Opciones:
- **PinVerificationException**: Este nombre indica claramente que el error está relacionado con la verificación del PIN.
- **PinAuthenticationException**: Similar al anterior, pero pone más énfasis en el proceso de autenticación.
- **InvalidPinException**: Este nombre sugiere que el PIN proporcionado es inválido, lo que podría ser una de las razones por las que se produce el error.
- **PinProcessingException**: Un nombre más general que puede ser utilizado si el error ocurre en cualquier punto del proceso que involucra el PIN, no solo en la verificación o autenticación.
- **PinErrorException**: Este es un nombre más genérico, pero aún proporciona la idea de que el error está relacionado con el PIN.

2024-04-05 08:46 UTC, rubenmodamio commented on src/main/java/es/in2/wallet/domain/service/impl/PreAuthorizedServiceImpl.java
> +                .onErrorResume(e -> Mono.error(new InvalidCredentialsException("Incorrect PIN or expired access token" + e)));
Changed to InvalidPinException

2024-04-05 08:51 UTC, oriolcanades submitted a review, later dismissed

2024-04-05 10:27 UTC, oriolcanades approved these changes, later dismissed

2024-04-05 11:02 UTC, oriolcanades approved these changes, later dismissed

2024-04-10 07:57 UTC, oriolcanades requested changes

2024-04-10 07:57 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/AuthorizationResponseServiceImpl.java
> +                    else {
Vigila con esta separación de if-esle. Lo ideal es:
```java
if(/*condition*/) {
  // code here
} else {
  // code here
}
```

2024-04-10 07:57 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/UserDataServiceImpl.java
> +
Vigila el formato ;)

2024-04-10 08:22 UTC, rubenmodamio commented on src/main/java/es/in2/wallet/domain/service/impl/UserDataServiceImpl.java
> +
He mejorado la estructura del método, pero con formato te refieres al uso del mono.zip?

2024-04-10 09:44 UTC, rubenmodamioin2 commented on src/main/java/es/in2/wallet/domain/service/impl/UserDataServiceImpl.java
> +
Mejorada la legibilidad

2024-04-11 08:54 UTC, oriolcanades approved these changes, later dismissed

2024-04-12 07:45 UTC, oriolcanades requested changes

2024-04-12 07:45 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/model/CredentialsBasicInfo.java
> +        @JsonProperty(AVAILABLE_FORMATS) List<String> availableFormats,
¿Por qué está en Mayusc?

2024-04-12 07:45 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/model/CredentialsBasicInfo.java
> +        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = ISO_8601_DATE_PATTERN)
¿Este será el estándar en todo el aplicativo?

2024-04-12 07:45 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/UserDataServiceImpl.java
> +                    JsonNode jsonNode = objectMapper.convertValue(vcAttribute.value(), JsonNode.class);
¿Por qué trabajamos con JsonNode y no se realiza un check del tipo de credencial y se mapea con su schema?

2024-04-12 07:45 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/UserDataServiceImpl.java
> +                    if (jsonNode.has(EXPIRATION_DATE) && !jsonNode.get(EXPIRATION_DATE).isNull()) {
Si no son variables estáticas y finales, ¿por qué usamos Mayusc. con SnakeCase?

2024-04-12 07:56 UTC, rubenmodamioin2 commented on src/main/java/es/in2/wallet/domain/model/CredentialsBasicInfo.java
> +        @JsonProperty(AVAILABLE_FORMATS) List<String> availableFormats,
Es un static final que esta en el messageUtils, la propiedad es la siguiente available_formats

2024-04-12 07:57 UTC, rubenmodamioin2 commented on src/main/java/es/in2/wallet/domain/service/impl/UserDataServiceImpl.java
> +                    if (jsonNode.has(EXPIRATION_DATE) && !jsonNode.get(EXPIRATION_DATE).isNull()) {
Este tambie un static final que esta en el messageUtils, la propiedad es expirationDate

2024-04-12 07:58 UTC, rubenmodamioin2 commented on src/main/java/es/in2/wallet/domain/model/CredentialsBasicInfo.java
> +        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = ISO_8601_DATE_PATTERN)
Si, ahora en el estándar siempre se usara este modelo para enviar los datos al frontal de las VCS, tanto en la visualización como en la presentación

2024-04-12 10:33 UTC, oriolcanades approved these changes

2024-04-15 07:53 UTC, merged