Hotfix v1.2.0
in2workspace/in2-wallet-core-api pull request #43
Opened 2024-06-04 09:33 UTC by rubenmodamioin2

2024-06-05 14:19 UTC, albertrodriguezdev commented on src/main/java/es/in2/wallet/infrastructure/broker/config/BrokerConfig.java
External domain is populate by internalUrl data

2024-06-06 12:24 UTC, oriolcanades submitted a review, later dismissed

2024-06-10 13:54 UTC, oriolcanades requested changes

2024-06-10 13:54 UTC, oriolcanades commented on src/main/java/es/in2/wallet/domain/service/impl/QrCodeProcessorServiceImpl.java
> -            if(DOME_LOGIN_REQUEST_PATTERN.matcher(qrContent).matches()){
¿Esto no podría implementarse con un switch?

2024-06-10 13:54 UTC, oriolcanades commented on src/main/java/es/in2/wallet/infrastructure/broker/config/BrokerConfig.java
> +    private String internal;
¿internal o internalDomain?

2024-06-10 14:17 UTC, albertrodriguezdev commented on src/main/java/es/in2/wallet/infrastructure/broker/config/BrokerConfig.java
> +    private String internal;
renamed to internalDomain

2024-06-11 06:24 UTC, rubenmodamioin2 commented on src/main/java/es/in2/wallet/domain/service/impl/QrCodeProcessorServiceImpl.java
> -            if(DOME_LOGIN_REQUEST_PATTERN.matcher(qrContent).matches()){
![Captura de pantalla 2024-06-11 082159](https://github.com/in2workspace/wallet-api/assets/145454887/7b1d9585-0e86-449d-b3e4-2b7c687b11ca)
En Java 17 no esta soportado los patterns en switch

2024-06-12 11:29 UTC, oriolcanades approved these changes

2024-06-17 07:09 UTC, merged